//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ctrviewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ctrviewer.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Bool_No {
            get {
                return ResourceManager.GetString("Bool_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Bool_Off {
            get {
                return ResourceManager.GetString("Bool_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Bool_On {
            get {
                return ResourceManager.GetString("Bool_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Bool_Yes {
            get {
                return ResourceManager.GetString("Bool_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or put BIGFILE.BIG in viewer&apos;s root folder,.
        /// </summary>
        internal static string GreetingInfo_Bigfile {
            get {
                return ResourceManager.GetString("GreetingInfo_Bigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or insert/mount CTR CD and use load level menu..
        /// </summary>
        internal static string GreetingInfo_CD {
            get {
                return ResourceManager.GetString("GreetingInfo_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to open menu..
        /// </summary>
        internal static string GreetingInfo_Escape {
            get {
                return ResourceManager.GetString("GreetingInfo_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put LEV/VRM files in levels folder,.
        /// </summary>
        internal static string GreetingInfo_LevFiles {
            get {
                return ResourceManager.GetString("GreetingInfo_LevFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ctr models go to models folder.
        /// </summary>
        internal static string GreetingInfo_Models {
            get {
                return ResourceManager.GetString("GreetingInfo_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No levels loaded..
        /// </summary>
        internal static string GreetingInfo_NoLevels {
            get {
                return ResourceManager.GetString("GreetingInfo_NoLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement PNG textures go to newtex folder..
        /// </summary>
        internal static string GreetingInfo_Replacements {
            get {
                return ResourceManager.GetString("GreetingInfo_Replacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTR-tools: Crash Team Racing (PS1) level viewer.
        /// </summary>
        internal static string GreetingInfo_Title {
            get {
                return ResourceManager.GetString("GreetingInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        internal static string MainMenu_GeneralOptions {
            get {
                return ResourceManager.GetString("MainMenu_GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart mode.
        /// </summary>
        internal static string MainMenu_KartMode {
            get {
                return ResourceManager.GetString("MainMenu_KartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MainMenu_Language {
            get {
                return ResourceManager.GetString("MainMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level options.
        /// </summary>
        internal static string MainMenu_LevelOptions {
            get {
                return ResourceManager.GetString("MainMenu_LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load level.
        /// </summary>
        internal static string MainMenu_LoadLevel {
            get {
                return ResourceManager.GetString("MainMenu_LoadLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MainMenu_Quit {
            get {
                return ResourceManager.GetString("MainMenu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string MainMenu_Resume {
            get {
                return ResourceManager.GetString("MainMenu_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day.
        /// </summary>
        internal static string MainMenu_TimeOfDay {
            get {
                return ResourceManager.GetString("MainMenu_TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video options.
        /// </summary>
        internal static string MainMenu_VideoOptions {
            get {
                return ResourceManager.GetString("MainMenu_VideoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuGeneric_Back {
            get {
                return ResourceManager.GetString("MenuGeneric_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string TimeOfDay_Day {
            get {
                return ResourceManager.GetString("TimeOfDay_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string TimeOfDay_Evening {
            get {
                return ResourceManager.GetString("TimeOfDay_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string TimeOfDay_Night {
            get {
                return ResourceManager.GetString("TimeOfDay_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 FPS.
        /// </summary>
        internal static string VideoMenu_30fps {
            get {
                return ResourceManager.GetString("VideoMenu_30fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisotropy level.
        /// </summary>
        internal static string VideoMenu_Anisotropy {
            get {
                return ResourceManager.GetString("VideoMenu_Anisotropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antialias.
        /// </summary>
        internal static string VideoMenu_Antialias {
            get {
                return ResourceManager.GetString("VideoMenu_Antialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backface culling.
        /// </summary>
        internal static string VideoMenu_BackfaceCulling {
            get {
                return ResourceManager.GetString("VideoMenu_BackfaceCulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Paths.
        /// </summary>
        internal static string VideoMenu_BotPaths {
            get {
                return ResourceManager.GetString("VideoMenu_BotPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show camera position.
        /// </summary>
        internal static string VideoMenu_CameraPosition {
            get {
                return ResourceManager.GetString("VideoMenu_CameraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show console.
        /// </summary>
        internal static string VideoMenu_Console {
            get {
                return ResourceManager.GetString("VideoMenu_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosseyed.
        /// </summary>
        internal static string VideoMenu_Crosseyed {
            get {
                return ResourceManager.GetString("VideoMenu_Crosseyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture filtering.
        /// </summary>
        internal static string VideoMenu_Filtering {
            get {
                return ResourceManager.GetString("VideoMenu_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Objects.
        /// </summary>
        internal static string VideoMenu_GameObjects {
            get {
                return ResourceManager.GetString("VideoMenu_GameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate mipmaps.
        /// </summary>
        internal static string VideoMenu_GenerateMipmaps {
            get {
                return ResourceManager.GetString("VideoMenu_GenerateMipmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal PSX Resolution (512x216).
        /// </summary>
        internal static string VideoMenu_InternalResolution {
            get {
                return ResourceManager.GetString("VideoMenu_InternalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible Meshes.
        /// </summary>
        internal static string VideoMenu_InvisibleMeshes {
            get {
                return ResourceManager.GetString("VideoMenu_InvisibleMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuadFlag.
        /// </summary>
        internal static string VideoMenu_QuadFlag {
            get {
                return ResourceManager.GetString("VideoMenu_QuadFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render BSP Branches.
        /// </summary>
        internal static string VideoMenu_RenderBranches {
            get {
                return ResourceManager.GetString("VideoMenu_RenderBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture replacements.
        /// </summary>
        internal static string VideoMenu_Replacements {
            get {
                return ResourceManager.GetString("VideoMenu_Replacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skybox.
        /// </summary>
        internal static string VideoMenu_Skybox {
            get {
                return ResourceManager.GetString("VideoMenu_Skybox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereoscopic mode (VR).
        /// </summary>
        internal static string VideoMenu_StereoMode {
            get {
                return ResourceManager.GetString("VideoMenu_StereoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle LoD.
        /// </summary>
        internal static string VideoMenu_ToggleLod {
            get {
                return ResourceManager.GetString("VideoMenu_ToggleLod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex lighting.
        /// </summary>
        internal static string VideoMenu_VertexLighting {
            get {
                return ResourceManager.GetString("VideoMenu_VertexLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Tree.
        /// </summary>
        internal static string VideoMenu_VisibilityTree {
            get {
                return ResourceManager.GetString("VideoMenu_VisibilityTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSync/FPS lock.
        /// </summary>
        internal static string VideoMenu_Vsync {
            get {
                return ResourceManager.GetString("VideoMenu_Vsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string VideoMenu_Water {
            get {
                return ResourceManager.GetString("VideoMenu_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        internal static string VideoMenu_Windowed {
            get {
                return ResourceManager.GetString("VideoMenu_Windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        internal static string VideoMenu_Wireframe {
            get {
                return ResourceManager.GetString("VideoMenu_Wireframe", resourceCulture);
            }
        }
    }
}
